-- 코드를 작성해주세요

SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO C
JOIN (
    SELECT A.ITEM_ID
    FROM ITEM_TREE A
    LEFT OUTER JOIN ITEM_TREE B
    ON A.ITEM_ID = B.PARENT_ITEM_ID
    WHERE B.PARENT_ITEM_ID IS NULL
) ZZ 
ON C.ITEM_ID = ZZ.ITEM_ID
ORDER BY C.ITEM_ID DESC