# -- 코드를 작성해주세요

SELECT C.FISH_COUNT, B.FISH_NAME
FROM FISH_NAME_INFO B
RIGHT OUTER JOIN (
    SELECT COUNT(1) AS FISH_COUNT, A.FISH_TYPE
    FROM FISH_INFO A
    GROUP BY A.FISH_TYPE
) C
ON B.FISH_TYPE = C.FISH_TYPE
ORDER BY C.FISH_COUNT DESC