# -- 코드를 작성해주세요

SELECT C.FISH_COUNT, B.FISH_NAME
FROM FISH_NAME_INFO B
RIGHT OUTER JOIN (
    SELECT COUNT(1) AS FISH_COUNT, A.FISH_TYPE
    FROM FISH_INFO A
    GROUP BY A.FISH_TYPE
) C
ON B.FISH_TYPE = C.FISH_TYPE
ORDER BY C.FISH_COUNT DESC

-- 아마도 FISH INFO에는 있는데 FISH_NAME_INFO에는 없는 컬럼이 있는듯 하다...
-- 맘에 안드는데.. 