-- 코드를 입력하세요

-- 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트를 출력하는 SQL문을 작성해주세요.
-- 결과는 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 대여 기록 ID를 기준으로 내림차순 정렬해주세요.



# SELECT 
# A.*, C.*
# # A.DAILY_FEE,
# #     B.HISTORY_ID,
#     # (DATEDIFF(END_DATE,START_DATE)+1) AS DAY
# FROM 
# CAR_RENTAL_COMPANY_CAR A
# LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
# ON A.CAR_ID = B.CAR_ID
# LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
# ON A.CAR_TYPE = C.CAR_TYPE
# WHERE 
# A.CAR_TYPE = '트럭' AND




# SELECT 

# A.DAILY_FEE,
# B.HISTORY_ID,
# (DATEDIFF(END_DATE,START_DATE)+1) AS DAY
# FROM 
# CAR_RENTAL_COMPANY_CAR A
# LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
# ON A.CAR_ID = B.CAR_ID


SELECT HISTORY_ID, ROUND(DAILY_FEE * DAY * DISCOUNT*0.01) AS FEE
FROM (
SELECT A.DAILY_FEE,
    B.HISTORY_ID,
    (DATEDIFF(END_DATE,START_DATE)+1) DAY,
    CASE WHEN (DATEDIFF(END_DATE,START_DATE)+1) >=90 THEN '90일 이상'
         WHEN (DATEDIFF(END_DATE,START_DATE)+1) >=30 THEN '30일 이상'
         WHEN (DATEDIFF(END_DATE,START_DATE)+1) >=7 THEN '7일 이상'
         ELSE '' END AS DAY_STR,
    COALESCE(
    (SELECT 100-DISCOUNT_RATE 
     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN TT 
     WHERE TT.CAR_TYPE ='트럭' AND TT.DURATION_TYPE = DAY_STR),100) AS DISCOUNT
FROM 
CAR_RENTAL_COMPANY_CAR A
LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
WHERE 
A.CAR_TYPE = '트럭'
) MM
ORDER BY FEE DESC, HISTORY_ID DESC
