-- 코드를 작성해주세요

# SELECT  A.* ,B.*,  bin(A.code) , bin(B.SKILL_CODE)
# # B.ID,B.EMAIL,B.FIRST_NAME, B.LAST_NAME
# FROM SKILLCODES A, DEVELOPERS B
# WHERE A.NAME ='Python' 
# OR A.NAME = 'C#'
# AND (B.SKILL_CODE & A.CODE) <>0
# ORDER BY B.ID ASC


select DISTINCT C.ID,C.EMAIL,C.FIRST_NAME,C.LAST_NAME
from (
    SELECT A.CODE
    FROM SKILLCODES A
    WHERE A.NAME = 'Python'
    OR A.NAME = 'C#'
)B , DEVELOPERS C
WHERE C.SKILL_CODE & B.CODE <> 0
ORDER BY C.ID ASC