-- 코드를 작성해주세요
SELECT D.YEAR, (D.MS - C.SIZE_OF_COLONY) AS YEAR_DEV,C.ID
FROM 
    ECOLI_DATA C, 
    (SELECT YEAR, MAX(SIZE_OF_COLONY) AS MS
    FROM 
        (
            SELECT A.ID, A.SIZE_OF_COLONY, YEAR(A.DIFFERENTIATION_DATE) AS YEAR
            FROM ECOLI_DATA A
        ) B
    GROUP BY YEAR) D
WHERE YEAR(C.DIFFERENTIATION_DATE) = D.YEAR
ORDER BY D.YEAR ASC, YEAR_DEV ASC