-- 코드를 작성해주세요



SELECT COUNT(1) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM(
    SELECT FISH_TYPE, 
        CASE WHEN LENGTH IS NULL THEN 10
            ELSE LENGTH END AS LENGTH
    FROM FISH_INFO A
) ZZ
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE ASC


# SELECT COUNT(1) AS FISH_COUNT, FISH_TYPE, AVG(LENGTH) AS AVG_LENGTH
# FROM FISH_INFO
# GROUP BY FISH_TYPE
# HAVING AVG_LENGTH >=33