name: Sync with CodingStudy

on:
  push:
    branches:
      - main  # SolvePS의 main 브랜치에 push될 때만 동작

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout SolvePS repository
      uses: actions/checkout@v2
      
    - name: Set up Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Clone CodingStudy repository
      run: |
        git clone https://github.com/ghrbs0437/CodingStudy.git
        cd CodingStudy
        git remote set-url origin https://ghrbs0437:${{ secrets.AUTO_PUSH }}@github.com/ghrbs0437/CodingStudy.git

    - name: Sync files
      run: |
        rsync -av --delete --exclude='.github' ./ CodingStudy/PS/
        cd CodingStudy
        git add PS/
        git commit -m "Sync from SolvePS: ${{ github.sha }}"
        git push origin main
