name: Sync with CodingStudy
  
on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # 레포지토리의 코드를 체크아웃
  
      - name: show directory
        run : |
          ls -al

      - name: Set up Git
        env: 
          PAT : ${{ secrets.AUTO_PS_PUSH }}
        run: |
          git config --global user.name "YHK[BOT]"
          git config --global user.email "YHK[BOT]@no.reply"
          git remote set-url origin https://ghrbs0437:$PAT@github.com/ghrbs0437/CodingStudy.git

      - name: Get the last commit message
        id: get_commit_msg
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)  # 마지막 커밋 메시지를 가져옴
          echo $COMMIT_MSG
          
      - name : push 
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_PS_PUSH }}
        run: |
          echo "###PUSH 프로세스 시작..###"
          echo $COMMIT_MSG
          rsync -av --delete ./SWEA ./PS/
          rsync -av --delete ./백준 ./PS/
          rsync -av --delete ./프로그래머스 ./PS/
          if git diff --cached --quiet; then
            ehco "NO Changes to commit."
            exit 0
          fi
          git add PS/  # ps 폴더에 변경된 파일들을 추가
          git commit -m "$COMMIT_MSG" 
          git push origin main
