name: Sync with CodingStudy

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
  pages: write
  
on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # 레포지토리의 코드를 체크아웃

      - name: Set up Git
        run: |
          git config --global user.name "YHK[BOT]"
          git config --global user.email "YHK[BOT]@no.reply"
          
      - name: Get the last commit message
        id: get_commit_msg
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_PS_PUSH }}
        run: |
          git config --global user.name "YHK[BOT]"
          git config --global user.email "YHK[BOT]@no.reply"
          git remote set-url origin https://ghrbs0437:${{ secrets.AUTO_PS_PUSH }}@github.com/ghrbs0437/CodingStudy.git
          COMMIT_MSG=$(git log -1 --pretty=%B)  # 마지막 커밋 메시지를 가져옴
          
          rsync -av --delete ./SWEA PS/
          git add PS/  # ps 폴더에 변경된 파일들을 추가
          git commit -m "$COMMIT_MSG" 
          
          git push origin main
