name: Sync with CodingStudy
  
on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # 레포지토리의 코드를 체크아웃
  
      - name: show directory
        run : |
          ls -al

      - name: Set up Git
        run: |
          git config --global user.name "YHK[BOT]"
          git config --global user.email "YHK[BOT]@no.reply"
          
      - name : push 
        env:
          PAT : ${{ secrets.AUTO_PS_PUSH }}
          GITHUB_TOKEN: ${{ secrets.AUTO_PS_PUSH }}
        run: |
          echo "###PUSH 프로세스 시작..###"
          COMMIT_MSG=$(git log -1 --pretty=%B)  # 마지막 커밋 메시지를 가져옴
          echo $COMMIT_MSG
          echo "$COMMIT_MSG"
          rsync -av --delete ./SWEA ./PS/
          rsync -av --delete ./백준 ./PS/
          rsync -av --delete ./프로그래머스 ./PS/
          #  if git diff --cached --quiet; then
          #    echo "NO Changes to commit."
          #    exit 0
          #  fi
          git remote set-url origin https://$PAT@github.com/ghrbs0437/CodingStudy.git
          git add PS/  # ps 폴더에 변경된 파일들을 추가
          git commit -m "AUTO_$COMMIT_MSG" 
          git push origin main
