name: PS_AUTO_PUSH

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  push-to-TIL:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config --global user.name 'YHK[bot]'
          git config --global user.email 'ghrbs0437@no.reply'
      - name: Push changes
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_PS_PUSH }}
        run: |
          git remote add TIL https://ghrbs0437:${{ secrets.AUTO_PS_PUSH }}@github.com/ghrbs0437/CodingStudy.git
          git push TIL main --force 
