name: PS_AUTO_PUSH

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  push-to-TIL:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config --global user.name 'YHK[bot]'
          git config --global user.email 'ghrbs0437@no.reply'
          git remote add TIL https://github.com/ghrbs0437/Study_Programmers.git
      - name: Push changes
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_PS_PUSH }}
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: 'output'
          destination-github-username: 'ghrbs0437'
          destination-repository-name: 'CodingStudy_'
          commit-message: 'Auto Push Test'
          target-branch: master
          target-directory: 'PS'
