name: PS_AUTO_PUSH

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
        API_TOKEN_GITHUB: ${{ secrets.AUTO_PS_PUSH }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config --global user.name 'YHK[bot]'
          git config --global user.email 'ghrbs0437@no.reply'
      - name: Commit changes
        run: |
          git add .
          git commit -m "AutoPs Push"
      - name: Push changes
        run: |
          git push https://github.com/ghrbs0437/CodingStudy_.git
