name: Push specific folder to another repo

on:
  push:
    branches: [main]

jobs:
  push-to-another-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Contigure git
        run: |
          git config --global user.name 'YHK[BOT]'
          git config --global user.email 'ghrbs0437[BOT]@no.reply'
        
      - name: Add target repository as a remote
        run: |
          git remote add target_repo https://github.com/ghrbs0437/CodingStudy.git
          git fetch target_repo

      - name: Push changes to the target repository
        run: |
          git push target_repo main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_PS_PUSH }}  # SolvePS 리포지토리의 secret
