name: PS_AUTO_PUSH

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run:  sh ./build.sh 
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_PS_PUSH }}
        with:
          source-directory: 'output'
          destination-github-username: 'ghrbs0437'
          destination-repository-name: 'CodingStudy_'
          user-email: YHK_AUTO@no.reply
          target-branch: main
          target-directory : 'PS'
