name: Push specific folder to another repo

on:
  push:
    branches: [main]

jobs:
  push-to-another-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Push specific directory to CodingStudy repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_PS_PUSH }}  # SolvePS 리포지토리의 secret
        with:
          # 푸시할 대상 리포지토리 정보
          destination-github-username: 'ghrbs0437'
          destination-repository-name: 'CodingStudy'
          # 커밋 메시지 설정
          commit-message: ${{ github.event.commits[0].message }}
          # 타겟 브랜치 및 디렉토리 설정
          target-branch: 'master'
          # target-directory: 'SWEA'
